workflows:
  release-workflow:
    name: Release Workflow
    triggers:
      - push:
          branches:
            only:
              - release
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    environment:
      vars:
        BUILD_MODE: "release"

  develop-workflow:
    name: Develop Workflow
    triggers:
      - push:
          branches:
            only:
              - develop
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Run debug build
        script: flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
    environment:
      vars:
        BUILD_MODE: "debug"
