workflows:
  release-workflow:
    name: Release Workflow
    branch: release
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    environment:
      vars:
        BUILD_MODE: "release"

  develop-workflow:
    name: Develop Workflow
    branch: develop
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Run debug build
        script: flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
    environment:
      vars:
        BUILD_MODE: "debug"
